AMF =
{
    INSTANCE_ID = 4;
    PID_DIRECTORY = "/var/run";
    AMF_NAME = "OIWIRELESS-AMF";
    LOG_LEVEL = "debug";
    RELATIVE_CAPACITY = 30;
    STATISTICS_TIMER_INTERVAL = 20;
    CORE_CONFIGURATION =
    {
        EMERGENCY_SUPPORT = "false";
    };
    GUAMI =
    {
        MCC = "466";
        MNC = "92";
        RegionID = "128";
        AMFSetID = "4";
        AMFPointer = "1";
    };
    SERVED_GUAMI_LIST =
    (
        {
            MCC = "466";
            MNC = "92";
            RegionID = "128";
            AMFSetID = "4";
            AMFPointer = "0";
        }
    );
    PLMN_SUPPORT_LIST =
    (
        {
            MCC = "466";
            MNC = "92";
            TAC = 100;
            SLICE_SUPPORT_LIST =
            (
                {
                    SST = 1;
                    SD = "0xFFFFFF";
                }
            );
        }
    );
    INTERFACES =
    {
        NGAP_AMF =
        {
            INTERFACE_NAME = "eth0";
            IPV4_ADDRESS = "read";
            PORT = 38412;
            PPID = 60;
        };
        SBI =
        {
            INTERFACE_NAME = "eth0";
            IPV4_ADDRESS = "read";
            PORT = 8004;
            API_VERSION = "v1";
            HTTP2_PORT = 8404;
            SMF_INSTANCES_POOL =
            (
                {
                    SMF_INSTANCE_ID = 5;
                    IPV4_ADDRESS = "172.11.200.15";
                    PORT = 8005;
                    HTTP2_PORT = 8405;
                    VERSION = "v1";
                    FQDN = "smf";
                    SELECTED = "true";
                }
            );
        };
        NRF =
        {
            IPV4_ADDRESS = "127.0.0.10";
            PORT = 8010;
            API_VERSION = "v1";
        };
        AUSF =
        {
            IPV4_ADDRESS = "172.11.200.13";
            PORT = 8003;
            API_VERSION = "v1";
        };
        UDM =
        {
            IPV4_ADDRESS = "172.11.200.12";
            PORT = 8002;
            API_VERSION = "v2";
        };
    };
    SUPPORT_FEATURES =
    {
        NF_REGISTRATION = "no";
        NRF_SELECTION = "no";
        EXTERNAL_NRF = "no";
        SMF_SELECTION = "no";
        EXTERNAL_AUSF = "no";
        EXTERNAL_UDM = "no";
        EXTERNAL_NSSF = "no";
        USE_FQDN_DNS = "no";
        USE_HTTP2 = "no";
    };
    AUTHENTICATION =
    {
        MYSQL_server = "172.11.200.10";
        MYSQL_user = "root";
        MYSQL_pass = "123456";
        MYSQL_db = "amfusers";
        RANDOM = "true";
    };
    NAS =
    {
        ORDERED_SUPPORTED_INTEGRITY_ALGORITHM_LIST =
        [
            "NIA2",
            "NIA1",
            "NIA0"
        ];
        ORDERED_SUPPORTED_CIPHERING_ALGORITHM_LIST =
        [
            "NEA0",
            "NEA1",
            "NEA2"
        ];
    };
};
