SPGW-U =
{
    INSTANCE = 10;
    PID_DIRECTORY = "/var/run";
    LOG_LEVEL = "debug";
    INTERFACES =
    {
        S1U_S12_S4_UP =
        {
            INTERFACE_NAME = "eth0";
            IPV4_ADDRESS = "read";
            SCHED_PARAMS =
            {
                SCHED_POLICY = "SCHED_FIFO";
                SCHED_PRIORITY = 88;
                POOL_SIZE = 3;
            };
        };
        SX =
        {
            INTERFACE_NAME = "eth0";
            IPV4_ADDRESS = "read";
            SCHED_PARAMS =
            {
                SCHED_POLICY = "SCHED_FIFO";
                SCHED_PRIORITY = 88;
                POOL_SIZE = 1;
            };
        };
        SGI =
        {
            INTERFACE_NAME = "eth0";
            IPV4_ADDRESS = "read";
            SCHED_PARAMS =
            {
                SCHED_POLICY = "SCHED_FIFO";
                SCHED_PRIORITY = 98;
                POOL_SIZE = 3;
            };
        };
    };
    SNAT = "yes";
    PDN_NETWORK_LIST =
    (
        {
            NETWORK_IPV4 = "192.169.0.0/16";
        }
    );
    SPGW-C_LIST =
    (
        {
            IPV4_ADDRESS = "172.11.200.15";
        }
    );
    NON_STANDART_FEATURES =
    {
        BYPASS_UL_PFCP_RULES = "no";
    };
    SUPPORT_5G_FEATURES =
    {
        ENABLE_5G_FEATURES = "yes";
        REGISTER_NRF = "no";
        USE_FQDN_NRF = "no";
        UPF_FQDN_5G = "no";
        NRF =
        {
            IPV4_ADDRESS = "127.0.0.1";
            PORT = 8030;
            HTTP_VERSION = 1;
            API_VERSION = "v1";
        };
        UPF_INFO =
        (
            {
                NSSAI_SST = 1;
                NSSAI_SD = "0xFFFFFF";
                DNN_LIST =
                (
                    {
                        DNN = "default";
                    }
                );
            },
            {
                NSSAI_SST = 1;
                NSSAI_SD = "0xFFFFFF";
                DNN_LIST =
                (
                    {
                        DNN = "ims";
                    }
                );
            },
            {
                NSSAI_SST = 1;
                NSSAI_SD = "0xFFFFFF";
                DNN_LIST =
                (
                    {
                        DNN = "ctnet";
                    }
                );
            },
            {
                NSSAI_SST = 1;
                NSSAI_SD = "0xFFFFFF";
                DNN_LIST =
                (
                    {
                        DNN = "internet";
                    }
                );
            }
        );
    };
};
